import type { RoomState, RoundResult, SessionResult, PlayerPublic } from "./types";

/**
 * Socket.io event contract (client ⇄ server).
 *
 * CLIENT → SERVER
 *  join_room      { roomId | levelId, nickname, auth? }   → ack { ok, state | error }
 *  leave_room     {}
 *  submit_guess   { roundId, guessPct, lock: boolean }     → ack { ok }
 *      (sent while dragging with lock=false — the server keeps the latest
 *       position as the fallback — and once with lock=true to lock in)
 *  ping_time      { t0 }                                   → ack { t0, t1 }  (clock sync)
 *
 * SERVER → CLIENT
 *  room_state     RoomState           full snapshot (on join / phase change)
 *  player_joined  PlayerPublic
 *  player_left    { playerId }
 *  player_locked  { playerId, locked }
 *  round_start    { roundId, roundIndex, baseId, targetId, timerSec, endsAt, serverNow }
 *  round_result   RoundResult
 *  session_end    SessionResult
 *  tournament_update { ... }
 *  error_msg      { code, message }
 */

export interface JoinRoomPayload {
  roomId?: string;
  levelId?: number;
  nickname: string;
  /** Guest id generated by the client, persisted in localStorage. */
  guestId?: string;
  /** Signed token from /api/socket-token for signed-in users. */
  userToken?: string;
  inviteCode?: string;
}

export interface JoinRoomAck {
  ok: boolean;
  error?: string;
  state?: RoomState;
  playerId?: string;
}

export interface SubmitGuessPayload {
  roundId: string;
  /** Size rounds. */
  guessPct?: number;
  /** Duel rounds: the side the player tapped (always locks). */
  pick?: "a" | "b";
  lock: boolean;
}

export interface RoundStartPayload {
  roundId: string;
  roundIndex: number;
  baseId: string;
  targetId: string;
  timerSec: number;
  endsAt: number;
  serverNow: number;
  levelId: number;
  kind?: "size" | "duel";
}

export interface ServerToClientEvents {
  room_state: (s: RoomState) => void;
  player_joined: (p: PlayerPublic) => void;
  player_left: (p: { playerId: string }) => void;
  player_locked: (p: { playerId: string; locked: boolean }) => void;
  round_start: (p: RoundStartPayload) => void;
  round_result: (r: RoundResult) => void;
  session_end: (r: SessionResult) => void;
  tournament_update: (t: { tournamentId: string; status: string; stage: number; message: string; roomId?: string }) => void;
  error_msg: (e: { code: string; message: string }) => void;
  /** أشك (Shak) dominoes. */
  shak_state: (s: import("./shak").ShakPublicState) => void;
  /** Your own hand (sent only to you). */
  shak_hand: (h: { code: string; tiles: number[] }) => void;
  /** ONE WORD tables. */
  ow_state: (s: import("./oneword").OwPublicState) => void;
  /** The secret key — sent only to Spymasters. */
  ow_key: (k: { code: string; key: import("./oneword").OwColor[] | null }) => void;
  /** SQUAD RUSH rooms. */
  sq_meta: (m: import("./squad").SqMeta) => void;
  sq_snap: (s: import("./squad").SqWire | import("./squad").SqSnap) => void;
  /** ECHO HALLS. */
  eh_meta: (m: import("./echo").EchoMeta) => void;
  eh_snap: (s: import("./echo").EchoSnap2) => void;
  eh_event: (e: import("./echo").EchoEvent) => void;
  /** WebRTC voice set-up, relayed from another player (`from` = their wire number). */
  eh_signal: (p: { from: number; data: unknown }) => void;
  /** NEON DRIFT arenas. */
  nd_meta: (m: import("./neon").NeonMeta) => void;
  nd_snap: (s: import("./neon").NeonSnap) => void;
  /** SMUGGLERS tables. */
  sm_state: (s: import("./smuggle").SmugglePublicState) => void;
  /** Your own secret word(s) — sent only to you. */
  sm_secret: (s: { code: string; words: string[] }) => void;
  /** Your team's guesser chat (full recent history; empty for Spymasters). */
  ow_chat: (c: { code: string; team: import("./oneword").OwTeam | null; msgs: import("./oneword").OwChatMsg[] }) => void;
}

export interface ClientToServerEvents {
  join_room: (p: JoinRoomPayload, ack: (a: JoinRoomAck) => void) => void;
  leave_room: () => void;
  submit_guess: (p: SubmitGuessPayload, ack?: (a: { ok: boolean; error?: string }) => void) => void;
  ping_time: (p: { t0: number }, ack: (a: { t0: number; t1: number }) => void) => void;
  /** Create a host-run room. The creator becomes host. */
  create_room: (
    p: { settings: Partial<import("./custom").CustomRoomSettings>; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; roomId?: string; error?: string }) => void,
  ) => void;
  /** Host only: start the game (or play again after it ends). */
  host_start: (ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** Host only: change settings while waiting / between games. */
  host_update: (p: { settings: Partial<import("./custom").CustomRoomSettings> }, ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** أشك (Shak) dominoes tables. */
  shak_create: (
    p: { settings?: Partial<import("./shak").ShakSettings>; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; code?: string; error?: string }) => void,
  ) => void;
  shak_join: (
    p: { code: string; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; error?: string; playerId?: string; state?: import("./shak").ShakPublicState; hand?: number[] }) => void,
  ) => void;
  shak_leave: () => void;
  /** Host: add / remove a bot seat. */
  shak_bot: (p: { op: "add" | "remove" }, ack: (a: { ok: boolean; error?: string }) => void) => void;
  shak_settings: (p: { settings: Partial<import("./shak").ShakSettings> }, ack: (a: { ok: boolean; error?: string }) => void) => void;
  shak_start: (ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** Play tiles face-down. `number` is required only when starting a new pile. */
  shak_play: (p: { tiles: number[]; number?: number }, ack: (a: { ok: boolean; error?: string }) => void) => void;
  shak_pass: (ack: (a: { ok: boolean; error?: string }) => void) => void;
  shak_doubt: (ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** ONE WORD tables. */
  ow_create: (
    p: { settings?: Partial<import("./oneword").OwSettings>; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; code?: string; error?: string }) => void,
  ) => void;
  ow_join: (
    p: { code: string; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; error?: string; playerId?: string; state?: import("./oneword").OwPublicState; key?: import("./oneword").OwColor[] | null; chat?: import("./oneword").OwChatMsg[] }) => void,
  ) => void;
  ow_leave: () => void;
  ow_act: (p: import("./oneword").OwAction, ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** SQUAD RUSH rooms. */
  sq_create: (
    p: { settings?: Partial<import("./squad").SqSettings>; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; code?: string; error?: string }) => void,
  ) => void;
  sq_join: (
    p: { code: string; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; error?: string; playerId?: string; meta?: import("./squad").SqMeta }) => void,
  ) => void;
  sq_leave: () => void;
  sq_act: (p: import("./squad").SqAction, ack: (a: { ok: boolean; error?: string }) => void) => void;
  sq_input: (p: import("./squad").SqInput) => void;
  /** ECHO HALLS rooms. */
  eh_create: (
    p: { nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; code?: string; error?: string }) => void,
  ) => void;
  eh_join: (
    p: { code: string; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; error?: string; playerId?: string; n?: number; meta?: import("./echo").EchoMeta; spawn?: { x: number; z: number } }) => void,
  ) => void;
  eh_leave: () => void;
  /** Pick a teen / change outfit. Fails if another player already plays that teen. */
  eh_look: (p: { look: import("./echo").EchoLook }, ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** Go in / pick up a fuse / use the fuse box / play again. */
  eh_act: (p: import("./echo").EchoAct, ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** Voice relay (TURN) logins for this match. Empty list = keep what you have. */
  eh_ice: (ack: (a: { iceServers: { urls: string | string[]; username?: string; credential?: string }[] }) => void) => void;
  eh_state: (p: import("./echo").EchoState) => void;
  /** WebRTC voice set-up for one other player (`to` = their wire number). */
  eh_signal: (p: { to: number; data: unknown }) => void;
  /** Local play-testing only (server started with ECHO_DEBUG): move the Copy. */
  eh_debug: (p: { copy?: { x?: number; z?: number; state?: string; as?: number; target?: number | null } }) => void;
  /** A new piece of my own speech (labels only — the audio goes peer to peer). */
  eh_clip: (p: { id: number; ms: number; tags: import("./echo").ClipTag[] }) => void;
  /** Better labels for one of my pieces (speech-to-text). */
  eh_tag: (p: { id: number; tags: import("./echo").ClipTag[] }) => void;
  /** I received someone's piece. */
  eh_have: (p: { key: string }) => void;
  /** NEON DRIFT arenas. */
  nd_create: (
    p: { settings?: Partial<import("./neon").NeonSettings>; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; code?: string; error?: string }) => void,
  ) => void;
  nd_join: (
    p: { code: string; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; error?: string; playerId?: string; meta?: import("./neon").NeonMeta }) => void,
  ) => void;
  nd_leave: () => void;
  nd_act: (p: import("./neon").NeonAction, ack: (a: { ok: boolean; error?: string }) => void) => void;
  /** Steering: -1 left, 0 straight, 1 right — or `aim` (radians) to steer toward the mouse. Sent on change only. */
  nd_input: (p: { turn: number; boost: boolean; aim?: number | null }) => void;
  /** SMUGGLERS tables. */
  sm_create: (
    p: { settings?: Partial<import("./smuggle").SmuggleSettings>; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; code?: string; error?: string }) => void,
  ) => void;
  sm_join: (
    p: { code: string; nickname: string; guestId?: string; userToken?: string },
    ack: (a: { ok: boolean; error?: string; playerId?: string; state?: import("./smuggle").SmugglePublicState; words?: string[] }) => void,
  ) => void;
  sm_leave: () => void;
  sm_act: (p: import("./smuggle").SmuggleAction, ack: (a: { ok: boolean; error?: string }) => void) => void;
}
