import type { RoomState, RoundResult, SessionResult, PlayerPublic } from "./types";

/**
 * Socket.io event contract (client ⇄ server).
 *
 * CLIENT → SERVER
 *  join_room      { roomId | levelId, nickname, auth? }   → ack { ok, state | error }
 *  leave_room     {}
 *  submit_guess   { roundId, guessPct, lock: boolean }     → ack { ok }
 *      (sent while dragging with lock=false — the server keeps the latest
 *       position as the fallback — and once with lock=true to lock in)
 *  ping_time      { t0 }                                   → ack { t0, t1 }  (clock sync)
 *
 * SERVER → CLIENT
 *  room_state     RoomState           full snapshot (on join / phase change)
 *  player_joined  PlayerPublic
 *  player_left    { playerId }
 *  player_locked  { playerId, locked }
 *  round_start    { roundId, roundIndex, baseId, targetId, timerSec, endsAt, serverNow }
 *  round_result   RoundResult
 *  session_end    SessionResult
 *  tournament_update { ... }
 *  error_msg      { code, message }
 */

export interface JoinRoomPayload {
  roomId?: string;
  levelId?: number;
  nickname: string;
  /** Guest id generated by the client, persisted in localStorage. */
  guestId?: string;
  /** Signed token from /api/socket-token for signed-in users. */
  userToken?: string;
  inviteCode?: string;
}

export interface JoinRoomAck {
  ok: boolean;
  error?: string;
  state?: RoomState;
  playerId?: string;
}

export interface SubmitGuessPayload {
  roundId: string;
  /** Size rounds. */
  guessPct?: number;
  /** Duel rounds: the side the player tapped (always locks). */
  pick?: "a" | "b";
  lock: boolean;
}

export interface RoundStartPayload {
  roundId: string;
  roundIndex: number;
  baseId: string;
  targetId: string;
  timerSec: number;
  endsAt: number;
  serverNow: number;
  levelId: number;
  kind?: "size" | "duel";
}

export interface ServerToClientEvents {
  room_state: (s: RoomState) => void;
  player_joined: (p: PlayerPublic) => void;
  player_left: (p: { playerId: string }) => void;
  player_locked: (p: { playerId: string; locked: boolean }) => void;
  round_start: (p: RoundStartPayload) => void;
  round_result: (r: RoundResult) => void;
  session_end: (r: SessionResult) => void;
  tournament_update: (t: { tournamentId: string; status: string; stage: number; message: string; roomId?: string }) => void;
  error_msg: (e: { code: string; message: string }) => void;
}

export interface ClientToServerEvents {
  join_room: (p: JoinRoomPayload, ack: (a: JoinRoomAck) => void) => void;
  leave_room: () => void;
  submit_guess: (p: SubmitGuessPayload, ack?: (a: { ok: boolean; error?: string }) => void) => void;
  ping_time: (p: { t0: number }, ack: (a: { t0: number; t1: number }) => void) => void;
}
